export const MOVIES = {
    SET_SEARCH_PARAMS: 'SET_SEARCH_PARAMS',
    FETCH_SEARCHED_MOVIE: 'FETCH_SEARCHED_MOVIE',
    LOAD_MORE: 'LOAD_MORE',
    LOAD_MORE_SUCCESSFUL: 'LOAD_MORE_SUCCESSFUL',
    SET_SPECIFIC_MOVIE_ID: 'SET_SPECIFIC_MOVIE_ID'
}

export const SPECIFIC_MOVIE = {
    SET_ID: 'SET_ID',
    SET_INFO: 'SET_INFO',
    EXIT_SCREEN: 'EXIT_SCREEN'
}
